### ISSUE TITLE
add ability to set the emissions CLI flag to false

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#236]
Currently, IFF the emissions CLI flag is set to true will the taro daemon be set to mint an asset with possible, subsequent emissions.  Users are currently assuming that the same field can be set to false to prescribe an asset not have subsequent emissions.  This is causing repeated user errors and is is a reasonable so assumption.

The issue will be satisfied by tarod allowing the emissions CLI field to also accept `false`

**Comment by dstadulis** [comment]
people want to use it
consider removing the flag and use a new term to reset

**Comment by jharveyb** [comment]
Digging in to this, having `--enable_emission` present in the cmd sets the internal bool to `true`. It can also be set with `=false` and `=true`, as expected. But a cmd using `--enable_emission false` sets the internal bool to `true`, as `=` is not used and `--enable_emission` is present.

 I dug into the `urfave/cli` docs further and IIUC we don't have a straightforward way to reject cmds with bool flags like `--enable_emission` where the value is not explicitly set. We also don't have a great way to reject extra strings in a cmd, as `true` and `false` are here when not using `=`.
 
 Also, right now these extra strings in the cmd seem to cause parsing issues for following flags.
 
  For example, a command that should set the `group_key` and `enable_emission` flags:
  - `tap-2-c-test assets mint --type collectible --name unlimited --supply 1 --enable_emission false --group_key 0349d60c6689bbbb2ffc9b30b45b96a3d6e5fd5fd01c867344c0054f6105048241`
  - gRPC request made by CLI: `(*mintrpc.MintAssetRequest)(0xc0002ec3c0)(asset:{asset_type:COLLECTIBLE  name:"unlimited"  amount:1}  enable_emission:true)`
  - - The group key is totally unset, and `enable_emission` is incorrectly set.
  - `group_key` is still unset even if we use `=` like this: `tap-2-c-test assets mint --type collectible --name unlimited --supply 1 --enable_emission false --group_key=0349d60c6689bbbb2ffc9b30b45b96a3d6e5fd5fd01c867344c0054f6105048241`
  
Once we remove `false` in the cmd it is parsed correctly:

- `tap-2-c-test assets mint --type collectible --name unlimited --supply 1 --enable_emission --group_key=0349d60c6689bbbb2ffc9b30b45b96a3d6e5fd5fd01c867344c0054f6105048241`
- `(*mintrpc.MintAssetRequest)(0xc0002ecb80)(asset:{asset_type:COLLECTIBLE  name:"unlimited"  amount:1  group_key:"\x03I\xd6\x0cf\x89\xbb\xbb/\xfc\x9b0\xb4[\x96\xa3\xd6\xe5\xfd_\xd0\x1c\x86sD\xc0\x05Oa\x05\x04\x82A"}  enable_emission:true)`

In practice, `enable_emission` and `group_key` are mutually exclusive settings, but the CLI should reject cmds that use both instead of mis-parsing them.

**Comment by dstadulis** [comment]
Draft PR has "Command with no arguments" are properly rejected

wanting to initial issuance

**Comment by jharveyb** [comment]
Other planned CLI changes re: emission - replacing `enable_emission` with `new_grouped_asset` and `grouped_asset`. `new_grouped_asset` would be used for creating a new asset with emission enabled / that will become a group anchor.

For reissuance, this would require `grouped_asset` and one of `group_key` or `group_anchor`. So the only valid combinations would be:

`--new_grouped_asset`

`--grouped_asset` `--group_key`

`--grouped_asset` `--group_anchor`

Which IMO is a bit clearer than the current flag name `enable_emission`. Strong thoughts @ffranr @GeorgeTsagk  ?

**Comment by jharveyb** [comment]
Will also need some RPC changes and a new type; right now we don't display if an asset added to a batch before finalization has `enable_emission` set.
