### ISSUE TITLE
Currencies getting lost when minting multiple currencies with skip_batch in one block

### ISSUE THREAD

**Issue by snow884** [lightninglabs/taproot-assets#266]
When I try to minting multiple currencies in one block currencies I submitted for minting get "lost" and never appear
```
for i in {1..20}; do tarocli assets mint --type=normal --name=NewCurrencyFromLoop$i --meta="test minting number $i" --skip_batch --supply=10000$i; done
```

This returns:
```
{
    "batch_key": "036099a9139325a058325b1754967139ef50b21052cc3aef7a9dc95914981c4765"
}
{
    "batch_key": "02a51a403ce9b5dfa70d9e1ade216a52d48eea551f4aa194699cd8f80eb6db0fd1"
}
{
    "batch_key": "0300658b33d38d598c14f33305e2b905c1a5b45718bba010a9fada9f482a303cb2"
}
{
    "batch_key": "02b139344bccb3e63ab1178560adb35fd31672f5ef555f40ec25d97de067dd282b"
}
...
```

Wait for a 5 blocks as that should be long enough even on testnet.

```
$ tarocli assets balance | grep NewCurrencyFromLoop
```

only gives
```
"name": "NewCurrencyFromLoop1"
```

So all of the 20 currencies that were minted got lost.

I know that there is the options to enable batches but still it happens to be a lot that I have to submit multiple mint commands in one block.

**Comment by dstadulis** [comment]
## Summary
hey @snow884 if I understand your intention you'd like to mint assets `NewCurrencyFromLoop1..20` in a single block.

Your issue may be described as:
Calling `--skip_batch` after a minting call, but before a minting txn is included in a block, the daemon doesn't rewrite a bitcoin transaction with the subsequent minting events.

## Fixes
### Quick
The short term amelioration would be: remove `--skip_batch` from your loop.  Then all the minting transactions will be grouped together in a minting batch which ought to included `NewCurrencyFromLoop1..20` 

### Long Term
Longer term fix could be to either
1. Throw a warning when calling `mint` between a `mint` call but before a block which includes the first mint is reeived
2. Modify the minting function so that it rewrites the minting transaction if a subsequent `mint --skip_batch` is called to include the subsequent minting
3. Modify the minting function so that it uses a different UTXO to mint subsequent calls (I need to check on where the delta would be on this work)

**Comment by snow884** [comment]
Thank you for quick reply @dstadulis  . 

I will try minting the currencies without `--skip_batch`

**Comment by Roasbeef** [comment]
> When I try to minting multiple currencies in one block currencies I submitted for minting get "lost" and never appear

Yeah `skip_batch` means that you want to mine it asap, this won't make them all in a single block. You want to drop that, then let the batch "tick". 

We're also working on a way to atomically create assets in a singel batch as well: https://github.com/lightninglabs/taro/issues/233 cc @jharveyb

**Comment by jharveyb** [comment]
Should be fixed with https://github.com/lightninglabs/taproot-assets/releases/tag/v0.2.0
