### ISSUE TITLE
Add comprehensive versioning to all protocol elements and even/odd compliance structure

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#347]
### Background
---
As tapd is upgraded and the protocol evolves, there will be a need by clients to deduce if the versions of various protocol elements (addresses, proof files, etc) need to known about by taproot-asset clients prescriptively or if the version is merely an indication of an optional update.  In order for the prescription functionality of version to be "self authenticated" (i.e. knowable without being previously known), the versioning method of "it's ok to be odd" (e.g. odd version are optional, even version are mandatory) will be used (See lightning BOLTs: https://github.com/lightning/bolts/commit/296075ec96d7788c0cf598e0ac24ef2de8b4a3a4)

### Compatibility
---
Implementing this feature will be a breaking change which we tolerate because of tapd's alpha status and will render large upgrading and correctness benefits over all operations when the daemon progresses to beta status.

### Deliverables
---
- [ ] Add comprehensive versioning to all protocol elements and even/odd compliance structure
  - [x] Add versioning to `addr`
https://github.com/Roasbeef/bips/blob/da3049f2f65b1c1c2b2caa7164449192b791bd29/bip-tap-addr.mediawiki?plain=1#L87-L96
 - [x] #392
  https://github.com/lightninglabs/taproot-assets/blob/7a5d5cae25f980c0ead87c0578584eafee689624/proof/proof.go#L80

### Necessary preceding work
- [ ] https://github.com/Roasbeef/bips/pull/33
  - [ ] implementing a new version for `Asset`, V1, #381 which would include:
  - [ ] Replace the `Genesis` field with a 32-byte `AssetID`, where the genesis data is provided in the genesis proof.
  - [ ] Update the `GroupKey` field to be 32 bytes instead of 96, to store only the tweaked group key.
  - [ ] Update encode/decode for Witness to follow even/odd rules for v1 assets
  - [ ] Update the TLV types to be even/odd compliant instead of sequential as they are now.

### Open Questions
---
#### 1
>Would a revision to an existing odd version, which isn't necessary, mean that the version would skip the even amount and progress directly to the next odd number?

Assume it would.

#### [2](https://github.com/lightninglabs/taproot-assets/issues/347#issuecomment-1611678264)
>for any existing v0 asset, because a v1 asset requires a new proof format that includes asset_genesis_reveal and group_key_reveal, all proofs for a v0 asset would have to be recomputed to move this data out of the asset and into the proof file.

**Comment by jharveyb** [comment]
The first proposed change / PR for this will be in support of https://github.com/Roasbeef/bips/pull/33.

Specifically, implementing a new version for `Asset`, V1, which would include:

- Replace the `Genesis` field with a 32-byte `AssetID`, where the genesis data is provided in the genesis proof.
- Update the `GroupKey` field to be 32 bytes instead of 96, to store only the tweaked group key.
- Add a version field to the `Witness` struct, to support future versions of the Tap VM that may use different witness types.
- Update the TLV types to be even/odd compliant instead of sequential as they are now.

**Comment by jharveyb** [comment]
After further digging I plan to not add a version field for `Witness`, since validation in the VM is already versioned based on `Asset.ScriptVersion`, and the `Witness.TxWitness` field is just an array of byte slices, and therefore should provide flexibility for future script versions. The encode/decode for `Witness` will still be updated to follow even/odd rules for v1 assets though.

**Comment by jharveyb** [comment]
After initial work on adding this `Asset` v1 in a backwards-compatible way, and offline discussion yesterday, this will be implemented as a breaking change for v0.3.

Additional reasons to make this breaking are that, for any existing v0 asset, because a v1 asset requires a new proof format that includes `asset_genesis_reveal` and `group_key_reveal`, all proofs for a v0 asset would have to be recomputed to move this data out of the asset and into the proof file.

**Comment by jharveyb** [comment]
After further offline discussion about versioning & the current state of our encoders/decoders, this is the current understanding & plan for implementing these changes:

- Right now we can change our TLVs in a non-breaking fashion by appending type numbers and fields to the end of existing TLVs. The even/odd pattern for required/optional fields is not currently enforced at all, but can be added using existing code in the TLV library like https://github.com/lightningnetwork/lnd/blob/a6fc5d0753d6c28416725e9c5de29d15c7cbca0c/tlv/stream.go#L154.

- Many of these changes cross multiple packages in the project, but constructing and reviewing very large PRs slows down progress. Version testing and struct changes also are more isolated than implementing spec changes.

Given that, we can 'change the tires while driving' by splitting this work up into multiple PRs on a staging branch, that are individually testable:

- Add optional fields that will be needed for the new & final type struct (e.x. the asset ID field and key-only group key field), without adding any functionality to populate them. Include encode/decode support and test unknown version rejection.
- Implement the new functionality that uses these new fields, and include the appropriate tests. The fields being replaced should now be unused.
- Update the struct and encoder/decoder to remove the old fields and enforce TLV even/odd rules.

**Comment by dstadulis** [comment]
@guggero will assess if the address structs have sufficient checks

**Comment by jharveyb** [comment]
Walking through each package & struct:

`address/Tap` is missing version field and handling
`commitment/AssetCommitment` has version field but no handling
`commitment/AssetProof & commitment/TaprootAssetProof` have version field but no handling

`asset/SplitCommitment` ?

**Comment by ffranr** [comment]
This is one of the type hierarchies that we care about:

`proof.Proof` <- `proof.TaprootProof` <- `proof.CommitmentProof` <- `commitment.Proof` <- `commitment/AssetProof` & `commitment/TaprootAssetProof`

Changes to the v0.3 staging branch means that `proof.Proof` has correct version handling. Types other than `proof.Proof` in the above hierarchy are only present in that hierarchy. I don't think we need to add versioning to any of the other types in this hierarchy. Versioning in `proof.Proof` is sufficient.

**Comment by ffranr** [comment]
`commitment/AssetCommitment` has a "version" field but as in other types this field tracks the max asset version. It shouldn't require a version because the type is exclusively used as a field within `commitment/TapCommitment`.

**Comment by ffranr** [comment]
`commitment/SplitCommitment` and `commitment/TapCommitment` don't have `Encode`/`Decode` methods. Which means that they are only "exported", if at all, nested under structs which should handle versioning. Outcome: no change required for these structures where versioning is concerned.

**Comment by ffranr** [comment]
`mssmt.FullTree` and `mssmt.CompactedTree` don't have Encode/Decode methods. Which means that they are only "exported", if at all, nested under structs which should handle versioning. Outcome: no change required for these structures where versioning is concerned.

**Comment by ffranr** [comment]
Here's a list of structs which have `Encode`/`Decode` methods which might require versioning:

- [ ] `address.Tap`
- [ ] `asset.Genesis`
- [ ] `asset.Asset`
- [ ] `proof.Proof`
- [ ] `mssmt.CompressedProof`
- [ ] `proof.File`
- [ ] `proof.MetaReveal`
- [ ] `taproot.CommitmentProof`
- [ ] `taproot.TapscriptProof`
- [ ] `tx.TxMerkleProof`

**Comment by guggero** [comment]
I think if a data structure is only ever used within another data structure that has a version (e.g. `taproot.CommitmentProof` or `taproot.TapscriptProof` within `proof.Proof`) then we don't necessarily need a new version. Because if we ever need the content of those structures to be interpreted in a different way, then we would simply bump the version of the `proof.Proof` file instead.
So with the version added to the Address, the only place we might need to take a look at are the trees themselves (e.g. for database serialization).

**Comment by ffranr** [comment]
I think we've decided not to modify the existing TLV types to be even/odd.

In which case, I think we should close this issue. I'll ping the team for a second opinion.

**Comment by jharveyb** [comment]
Reopening since we decided in last planning to pursue the TLV changes for v0.3.
