### ISSUE TITLE
tapdb/universe: switch back to []byte for universe.Proof + universe.Leaf

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#625]
In [this commit](https://github.com/lightninglabs/taproot-assets/commit/192dff8d0993dd7fe2b74cd39c46665919c528da) we started to use the actual proof pointer, instead of just a blob to save on some encode/decode cycles during minting. However as we're seeing on mainnet now, we end up fully decoding the proof, just to turn around and fully serialize it to send over the RPC interface. 

We should go back to using `proof.Blob` as profiles show we end up generating a ton of garbage with the current appraoch.

**Comment by Roasbeef** [comment]
Along side this, we should add a benchamrk in the db so we can track allocations for some canned size proof.

**Comment by Roasbeef** [comment]
Here's an SVG that shows some of where we're allocating a lot of memory when serving proofs file: ![profile001](https://github.com/lightninglabs/taproot-assets/assets/998190/2bfb5bb7-59e3-4946-b711-444538c8c077)

Midterm, we want to go with memory mapping here: #147

**Comment by guggero** [comment]
@Roasbeef I took a quick look at this. And it looks like we need to at least decode the proof a single time, since we return the full asset in the `QueryProof` RPC call.
But I think we can save some decode/encode cycles by internally passing around both the proof blob (can memory map later) and the decoded asset (which excludes the asset meta).

Ran out of time unfortunately, but pushed the work in progress here: https://github.com/lightninglabs/taproot-assets/tree/query-proof
Doesn't even compile yet, but I think you should get the idea.

**Comment by jharveyb** [comment]
Resolved with #626.
