### ISSUE TITLE
[feature]: create an initial basic version of the `PriceOracle` RFQ service

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#777]
Parent issue: https://github.com/lightninglabs/taproot-assets/issues/683

The `PriceOracle` is a new RFQ subsystem service for retrieving the exchange rate between BTC and a counter currency. The service is queried by the RFQ `Negotiator` service.

**Comment by ffranr** [comment]
The unknowns I'd like to solve are:
1. How do I get from an asset ID/asset group to some bid/ask on a site like blockchain.com
2. How do I handle niche assets where I can't find a bid/ask on the internet.

Do we need meta data in the asset to the effect of "price this asset as this fiat currency"?

Any ideas @Roasbeef @jharveyb @dstadulis ?

**Comment by Roasbeef** [comment]
> How do I get from an asset ID/asset group to some bid/ask on a site like blockchain.com

From the code's PoV, it's an abstract interface it can use to obtain price data. It isn't aware of _where_ it's getting that data from, just that it can map a `(asset, volume)` pair into an acceptable price. 

The actual implementation can source data from pretty much anywhere. We'll fashion a standardized JSON/gRPC interface similar to the `feeurl` setting we have. A daemon won't ever need to source prices of an asset that it doesn't hold itself. 

> How do I handle niche assets where I can't find a bid/ask on the internet.

I don't think this is a concern. See above. 

The code can be written in an abstracted style, trusting that if a daemon has an asset, then it'll be able to obtain a relevant price for it. If not, then there'll be an error scenario where a user may need to manually update a config, or run a slim proxy to be able to obtain a quote. 

More concretely, I think this would take the form of a `PirceOracle` gRPC service that _`tapd`_ becomes a client of. We hit this endpoint whenever we need to obtain a price that isn't cache otherwise. This can also instead be configured as a normal REST endpoint returning JSON in w/e format. 

> Do we need meta data in the asset to the effect of "price this asset as this fiat currency"?

What would that look like in practice? I think, no? The logic of an oracle implementation itself can be very dynamic, and isn't really restricted by much. You can think of it just like fee estimation in a sense.
