### ISSUE TITLE
How to get metadata for batch that is currently pending / not finalized - or in general how to get metadata by meta_hash / meta_hash_str

### ISSUE THREAD

**Issue by weltitob** [lightninglabs/taproot-assets#798]
Hi the below cord works fine, however I do not understand how I should use https://lightning.engineering/api-docs/api/taproot-assets/taproot-assets/fetch-asset-meta to fetch asset meta based on a meta hash instead of an asset id // my asset ids only show up for finalized assets which means this only works for finalized assets but what about the taproot assets that are still in a batch??

I tried using the meta hash and the meta hash str as described in the documentation, none worked for me.

Can somebody please explain how I use metahash to get the metadata of my assets?

```
import requests
import codecs
import base64
import json
from requests.packages.urllib3.exceptions import InsecureRequestWarning



#DAS HIER IST APPLICABLE FÜR METADATEN VON BEREITS FINALIZED ASSETS ABER WAS IST MIt JENEN DIE NOCH GEBATCHT SIND


# Deaktivieren der Warnung über unsichere Anfragen
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

REST_HOST = 'mybitnet.com:8443'
MACAROON_PATH = './pythonfunctions/keys/tapd_admin.macaroon'

# Konvertieren der Asset-ID aus Base64 in Hex
asset_id = "x1FgXWAFqpUcLF9ArPtIOB6Kpr9eIme4YqMDdOU0Eak="
asset_id_2 = "2ps13PAMYxQtuObvqXxs4rIjKSTX+hqRDUws4auwJYQ="
decoded_bytes = base64.b64decode(asset_id_2)
hex_str = decoded_bytes.hex()
print(f"Hex string: {hex_str}")

url = f'https://{REST_HOST}/v1/taproot-assets/assets/meta/asset-id/{hex_str}'

# Lesen und Kodieren des Macaroon
macaroon = codecs.encode(open(MACAROON_PATH, 'rb').read(), 'hex')
headers = {'Grpc-Metadata-macaroon': macaroon}

# Durchführen der GET-Anfrage
response = requests.get(url, headers=headers, verify=False)  # 'verify=False' nur für Tests, nicht in Produktion verwenden

# Überprüfen der Antwort
if response.status_code == 200:
    try:
        # Decodieren der 'data' aus der JSON-Antwort
        response_data = response.json()  # Holt die Antwort als Dictionary
        print(response_data)
        decoded_data = base64.b64decode(response_data['data'])
        try:
            # Versuch, die decodierten Daten als JSON zu interpretieren
            json_data = json.loads(decoded_data)
            print("Decoded JSON data:", json_data)
        except json.JSONDecodeError:
            # Falls die Daten kein gültiges JSON sind, direkt ausgeben
            print("Decoded data is not valid JSON. Raw data:", decoded_data.decode())
    except KeyError:
        print("The response JSON does not contain 'data' key.")
else:
    print(f"Failed to fetch data. Status code: {response.status_code}")

```

**Comment by guggero** [comment]
Can you perhaps describe your use case a bit more? Because if you're just creating a batch that isn't finalized yet, why would you need to access the meta data that you just uploaded to create the batch? Or are there different users accessing this pending data at the same time?

It is correct that an asset ID is only known after it has been minted. The reason is that the first on-chain input used for the minting BTC transaction is hashed into the asset ID to make it globally unique.

You should be able to list the pending batches and get a response with all pending assets, including their meta data: https://lightning.engineering/api-docs/api/taproot-assets/mint/list-batches

Since the assets aren't finalized yet, they will not appear in the `FetchAssetMeta` call.

**Comment by guggero** [comment]
@weltitob can this be closed?

**Comment by weltitob** [comment]
> @weltitob can this be closed?

Yes thanks
