### ISSUE TITLE
[feature]/universe+rpc: add new command to push up proofs to universes

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#989]
**Is your feature request related to a problem? Please describe.**

Today we have `tapcli universe sync` which'll attempt to _fetch_ proofs from the target universe. 

When we mint, we'll also push out to all registered universe federation members. We'll also [maintain a log to ensure we can push out to the set of federation members reliably](https://github.com/lightninglabs/taproot-assets/blob/2d8d4849df66c9632038018a8da01a882be39baf/universe/auto_syncer.go#L300-L345). 

However there isn't an easy way to just push out an arbitrary proof. 

**Describe the solution you'd like**

We should add `tapcli universe push` or `tapcli universe insert` that targets a remote universe rather than the local on.

**Comment by dstadulis** [comment]
`tapcli universe push`
or
`tapcli universe broadcast`

appeal to me

**Comment by gijswijs** [comment]
What does `universe proofs insert` do if not this?

**Comment by guggero** [comment]
`tapcli universe proofs insert` inserts a proof into the _local_ universe. I think the goal of this issue is to have a command that uploads a proof from the local universe to a remove one (a single, specific proof instead of doing a full sync).

**Comment by jharveyb** [comment]
Another option is to use the `RpcUniverseRegistrar.UpsertProofLeaf` func, with a connection made to a server specified via CLI flags. You could connect via `NewRpcUniverseRegistrar()`.

**Comment by gijswijs** [comment]
As discussed with @jharveyb:

New rpc endpoint for the universe rpc: 'PushProof`, tapcli: `universe push`
The request should contain a `UniverseKey` so that we can query the issuance or transfer proof for a given asset from the local universe and a `ServerAddr` that we can use to connect to and push the proof. Alternatively we could assume that the universe is always a registered federation server and we can identify it by an ID.

We then use `universeProofQuery` to fetch the proof from the local universe.
https://github.com/lightninglabs/taproot-assets/blob/aa3d671f4bc4b7e14c44e4e172011d3740065bd3/cmd/tapcli/universe.go#L477-L478

And we push the proof to the remote universe, using `RpcUniverseRegistrar.UpsertProofLeaf`
https://github.com/lightninglabs/taproot-assets/blob/aa3d671f4bc4b7e14c44e4e172011d3740065bd3/universe_rpc_registrar.go#L83
